# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8319fdbc422cccc40c37adc4407cb49e6a8c1df9755accfd744be8de13103a271f1a748f157904ff4dc7e6cb1f2f83c0babe87eed2078be9aba1a45097ba908a

test:
  secret_key_base: 51e3249bbe9207272fa4f6157eecde576a7cafc50d87a844a33bb0eef7144c829b99afee92343284c68887289e97b90c2bc5be3199e5f42aa174379b5f563f54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
